name: sf_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get:
  get_storage: ^2.1.1 
  flutter_screenutil: 
  flutter_svg: ^2.0.10+1
  flutter_spinkit: ^5.2.0
  linear_progress_bar: ^1.1.1
  google_fonts: ^5.1.0
  flutter_otp_text_field: ^1.1.1
  password_strength_checker: ^1.2.2
  password_strength_indicator_plus: ^0.0.1
  password_strength_indicator:
  regexpattern: ^2.6.0
  image_picker: ^1.0.7
  smooth_page_indicator: ^1.1.0
  font_awesome_flutter: 10.7.0
  syncfusion_flutter_sliders: ^25.1.42
  dio: ^5.4.3+1
  connectivity_plus: ^6.0.3
  file_picker: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
